plugins {
    id 'com.android.application'
}

android {
    compileSdk 36

    defaultConfig {
        applicationId "io.github.pricescrawler.mobile"
        minSdk 26
        targetSdk 36
        versionCode 3
        versionName "0.1.3"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file(System.getenv("HOME") + "/keystore/upload-keystore.jks")
            storePassword System.getenv("KEYSTORE_PASSWORD")
            keyAlias System.getenv("KEY_ALIAS")
            keyPassword System.getenv("KEY_PASSWORD")
        }
    }

    buildTypes {
        debug {
            buildConfigField "String", "SERVER_URL", "\"${System.getenv("PRICES_CRAWLER_SERVER_URL_DEBUG") ?: project['prices.crawler.server.url.debug']}\""
        }
        release {
            buildConfigField "String", "SERVER_URL", "\"${System.getenv("PRICES_CRAWLER_SERVER_URL_RELEASE") ?: project['prices.crawler.server.url.release']}\""
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    namespace 'io.github.pricescrawler.mobile'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
}
